#!/bin/sh
DF_DIR=$(dirname "$0")
cd "${DF_DIR}"
export SDL_DISABLE_LOCK_KEYS=1 # Work around for bug in Debian/Ubuntu SDL patch.
#export SDL_VIDEO_CENTERED=1 # Centre the screen.  Messes up resizing.
export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}libGL.so.1:./set_ptracer_any.so"
./libs/Dwarf_Fortress "$@" # Go, go, go! :)

